### ISSUE TITLE
Holo and invisible blocks [BUG]

### ISSUE THREAD

**Issue by Daysmith** [PixyLT/PixySpawners#3] opened 2020-12-30 19:43 UTC
**Describe the bug**
i placed and stacked blaze spawners on a survival server, once i removed it with a diamond pickaxe enchanted with silk touch,, the holo sign was not removed and 2 invisible block not removable were replacing the stacked spawners.

**Comment by TitasPi** [comment] 2021-02-02 18:41
I noticed this bug. It's caused by other hologram plugins. At least that's the only reason I found for now.
You can remove holograms with this command /minecraft:kill @e[type=armor_stand,distance=..3] It will remove armor_stands in 3 blocks distance.
By the way, can you provide your plugin list and server version?

**Comment by TitasPi** [comment] 2021-06-27 20:42
Fixed in latest release

**Closed as completed by TitasPi** 2021-06-27 20:42 UTC
Labels: bug
